#!/bin/sh

DIR="$HOME/Pictures/Walls/"
BG="$(find "$DIR" -name '*.jpg' -o -name '*.png' -name '*.webp' | shuf -n 1)"

trans_type="grow"

# Name of the program to check
PROGRAM="swww-daemon"

# Check if the program is running
if pgrep "$PROGRAM" >/dev/null; then
	swww img "$BG" --resize fit --transition-fps 60 --transition-type $trans_type --transition-pos "$(hyprctl cursorpos)" --invert-y --transition-duration 2
else
	swww init && swww img "$BG" --resize fit --transition-fps 60 --transition-type $trans_type --transition-pos "$(hyprctl cursorpos)" --invert-y --transition-duration 2
fi